! frr/vtysh.conf
! конфигурация интегрированного режима vtysh
! всё хранится в одном frr.conf, демоны читают его через vtysh

service integrated-vtysh-config

hostname frr-branch
username root nopassword
