# wireguard/wg0-branch.conf — сторона филиала (frr-router)
# устанавливается на frr-branch контейнер

[Interface]
# адрес филиала в туннеле
Address = 10.13.13.2/24

# приватный ключ филиала
PrivateKey = REPLACE_WITH_REAL_PRIVATE_KEY_BRANCH

MTU = 1380

# маршрутизация через туннель к цод
PostUp   = ip rule add from 10.0.2.0/24 table 201; \
           ip route add 10.0.1.0/24 dev wg0 table 201; \
           ip route add 10.13.13.0/24 dev wg0

PostDown = ip rule del from 10.0.2.0/24 table 201; \
           ip route del 10.0.1.0/24 dev wg0 table 201

# peer: wireguard-сервер в цод
[Peer]
PublicKey = REPLACE_WITH_REAL_PUBLIC_KEY_DATACENTER

# endpoint публичный ip цод + порт wireguard
# в стенде это хост-машина с port-forwarding 51820
Endpoint = REPLACE_WITH_DATACENTER_PUBLIC_IP:51820

# весь трафик к цод и туннельной подсети через wireguard
AllowedIPs = 10.13.13.0/24, 10.0.1.0/24

# keepalive чтобы nat-сессия не закрывалась
# особенно важно для спутникового канала с длинными nat-таймаутами
PersistentKeepalive = 25